fail_fast: true
repos:

- repo: local
  hooks:
  - id: ruff-check
    name: ruff-check
    entry: ruff
    language: python
    types: [python]
    args: [check]

  - id: ruff-format
    name: ruff-format
    entry: ruff
    language: python
    types: [python]
    args: [format, --check]

  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]

  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: [--show-error-codes]
