repos:

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    args: ['--load-plugins', 'pylint_quotes']
    language: python
    types: [python]

  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: [--show-error-codes]
